# === Database Configuration ===
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=hAVyteCbmBqOLrAfYvNILgldsaTnrNZZ
spring.datasource.driver-class-name=org.postgresql.Driver


spring.application.name=Huerta-directa




# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
# Desactiva cach? para ver cambios sin reiniciar
spring.thymeleaf.cache=false


# Ubicaci?n y extensi ?n por defecto
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# (Opcional) Modo de plantillas
spring.thymeleaf.mode=HTML


logging.level.org.thymeleaf=TRACE


# Ruta para subir imágenes
upload.path=${UPLOAD_PATH}


# Tama?o m?ximo de archivo individual
spring.servlet.multipart.max-file-size=10MB
# Tama?o m?ximo de request completo
spring.servlet.multipart.max-request-size=10MB




mercadopago.access_token=${MERCADOPAGO_ACCESS_TOKEN}
mercadopago.public_key=${MERCADOPAGO_PUBLIC_KEY}
#mercadopago.success_url=http://localhost:8085/payment/success
#mercadopago.failure_url=http://localhost:8085/payment/failure
#mercadopago.pending_url=http://localhost:8085/payment/pending


# Puerto salida
server.port=${PORT:8080}


# URLs de tu aplicación
#app.base.url=http://localhost:8085


# URL de notificaciones (puede ser cualquier URL por ahora)
#mercadopago.notification.url=http://localhost:8085/api/notifications

